[package]
name = "dokan_project_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
toml = "0.8.19"
chrono = { version = "0.4.19", features = ["serde"] }
directories = "5.0.1"
